spring:
  freemarker:
    cache: false
    settings:
      number_format: 0

resources:
  chain:
   strategy:
     content:
       enabled: true
       paths: /**
   cache: false
   compressed: false
   enabled: false
  cache:
    cachecontrol:
      cache-public: false

server:
  tomcat:
    max-threads: 1000
    min-spare-threads: 100
    accept-count: 300
  connection-timeout: 30000

image:
  allow:
    type: png|jpg|jpeg|gif|bmp

jdbc:
  #ali
  url: 1F0030AD817F268AA38320EDE1AAF675BAE6DC822CECB43D22FD474D9539534977FD62D903270F80
  #localhost
  #url: 1F0030AD817F268A3FED02C0C1C1774D9B6F58676E382D14C8F6C5B39C12E02E
  username: D2A2150E6097A828
  password: 3C735B2B0AFD4442922583FF75513E75
  driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    maxLifetime: 120000