server:
  servlet:
    session:
      cookie:
        maxAge: 2592000
        httpOnly: false
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  profiles:
    active: ${activatedProperties}
  resources:
      chain:
       strategy:
         content:
           enabled: true
           paths: /**
       cache: true
       compressed: false
       enabled: true
      cache:
        cachecontrol:
          cache-public: true